### ISSUE TITLE
tag_generator script error

### ISSUE THREAD

**Issue by benjaminapetersen** [qian256/qian256.github.io#1]
Greetings!
Going through your [post](http://longqian.me/2017/02/09/github-jekyll-tag/) on manually generating tags, I copied down your script, ran it and:

```bash
$ python ./tag_generator.py
Traceback (most recent call last):
  File "./tag_generator.py", line 23, in <module>
    f = open(filename, 'r', encoding="utf8")
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by andy5995** [comment]
Same error. using `python3` got rid of it.

**Comment by bbookman** [comment]
Please fix,don't really want to switch python releases

**Comment by benjaminapetersen** [comment]
Its reasonable to require `python3` for a personal project, perhaps just point it out in the README as a doc & this is probably solved.

**Comment by qian256** [comment]
It should be fixed now. I tested with both Python 2 and 3
