### ISSUE TITLE
tag generation post improvement

### ISSUE THREAD

**Issue by streetturtle** [qian256/qian256.github.io#3]
Hi, just want to do a small remark regarding you post: [Jekyll Tags on Github Pages](http://longqian.me/2017/02/09/github-jekyll-tag/). Actually in the front matter section tags could be presented as list:

    tags:
      - jekyll
      - blog
      - github-page

This way it will be possible to have tags with spaces, like 'angular js'. 
Thanks for great post!

**Comment by razvn** [comment]
If you write them as 
```yaml
tags: [jekyll, blog, github-page, tag with space]
```
you can use the pulls requests I've just done. If I have some spare time I may take a look adding support for this kind of presentation too.

**Comment by arturomoncadatorres** [comment]
@streetturtle Feel free to look at [my implementation of how to collect the tags](https://github.com/arturomoncadatorres/arturomoncadatorres.github.io/blob/master/update_tags.py) (function `get_tags`) when they are structured as you mention. However, be aware that for now it only works if the tags are the last element of the post header.
